### ISSUE TITLE
Limit the amount of data sent to Bosun/OpenTSDB in each PUT request

### ISSUE THREAD

**Issue by rickynils** [evidentiae/logmetrics#5]
OpenTSDB has a setting for limiting the allowed HTTP content-length when submitting metrics. It should be able to configure the maximum amount of data logmetrics sends on each request, so we don't get rejections from Bosun/OpenTSDB.

I recently ran into this problem. The request from logmetrics exceeded 10 MB, which was the configured limit for OpenTSDB. So logmetrics only got a status 500 reply back. And kept re-sending the requests, but of course they kept failing. When I upped the limit in the OpenTSDB config, logmetrics submitted all earlier metrics (nice!).

**Comment by rickynils** [comment]
I think the submitted metrics can be gzipped too (see "Compressed Requests" in http://opentsdb.net/docs/build/html/api_http/index.html). But it will be more difficult to chunk up the PUT-requests in correct sizes then I guess.

**Comment by waern** [comment]
Is the idea to just add a chunk size to the logmetrics configuration and use that, or to query the max chunk size from the OpenTSDB API?

Regarding compression, I don't really see the problem. Here's what I think we should do:

1) Compress with gzip (using a Haskell library)
2) Chunk the data up in appropriately sized chunks.
3) Send the data using Content-Encoding: gzip and Transfer-Encoding: chunked (Wreq has a special API to support this).

**Comment by rickynils** [comment]
Chunk size in config is sufficient for now I think.

Ah, yes, OpenTSDB supports chunked requests, so your algorithm should work fine. I suggest implementing compressed chunks as part of this issue.

To test this, you add something like the following to https://github.com/evidentiae/logmetrics/blob/master/test/simple.nix#L53 :

```
  services.opentsdb = { 
    enable = true;
    config = ''
      tsd.http.request.enable_chunked  = true
      tsd.http.request.max_chunk = 1024
    ''; 
  };  
```
The chunk size is in bytes. You should see errors triggered in OpenTSDB if you let logmetrics send larger chunks than configured.

**Comment by waern** [comment]
Argh. Having implemented the scheme above and done some testing I finally discovered that "max_chunk" doesn't mean the max size of each chunk but the max size of the entire message, i.e. the content length of the entire (chunked) body! See https://github.com/OpenTSDB/opentsdb/issues/324.

We need to write an algorithm that splits all datapoints into a series of POST requests each containing a valid JSON list of datapoints, gzipped, smaller than 'max_chunk'.

**Comment by waern** [comment]
See https://github.com/evidentiae/logmetrics/commit/7e81edc34da76cc5476594fca7ee12ed5b2263db. Can you test if this solves your problem in production? I have tested that it works for small log data.

**Comment by waern** [comment]
Also, I should add that we apply compression assuming it will make the data smaller, which of course is not always the case but in practice for our datapoints I think it should be a safe assumption.

**Comment by rickynils** [comment]
Thanks! Will test it.

Just so I get this right: `metricsMaxBodySize` should be aligned with with OpenTSDB's `max_chunk` setting, and `metricsMaxChunkSize` can be used to keep the size of each TCP session down, right?

**Comment by rickynils** [comment]
... and I assume the sizes are in bytes?

**Comment by waern** [comment]
Yes, if you use OpenTSDB's chunked mode then `metricsMaxBodySize` should be aligned with `max_chunk`.  `metricsMaxChunkSize` is the max size of each HTTP chunk. Both sizes are in bytes.

**Comment by rickynils** [comment]
Working fine so far! Closing this issue
